### ISSUE TITLE
[suggestion] Allow for command execution before shutdown

### ISSUE THREAD

**Issue by fuzzyweapon** [coolsimulations/ServerStop#1]
For instance, I'd like to broadcast warnings at pre-configured times to let players know the server is shutting down.

I'd also like to issue another command in conjunction with this warning.  I have installed a mod that allows operators to lock the server (a connection gating mechanism) so it'd be nice to automatically use this command when issuing the warning of immanent shutdown so I can automatically gate new players or other players out of connecting during that period.

**Comment by coolsimulations** [comment]
Didn't see this until just now. Just making sure I understand what you're saying, you want to broadcast a message to the players letting them know the server is shutting down. Currently, a warning message is already being sent to all players at 5mins, 1min, 30sec, 10sec, 5sec, 4sec, 3sec, 2sec, and 1sec remaining before server shutdown. I haven't made this configurable due to the amount of lang translations needed, but if you want it so that the warnings are configurable I can take a look at it.

Also, you said have a mod which locks the sever. Not being familiar with that mod I assume it means that normal players cannot join when the server is locked except for operators. So you want it so that the warning message automatically locks the server? In order to do that I'd need to know what specific mod it is.

**Comment by coolsimulations** [comment]
Unless @fuzzyweapon provides more explanation I will close this issue in the next few days as ServerStop already sends a warning message.

**Comment by coolsimulations** [comment]
Issue closed due to inactivity. If you think that this issue is unresolved then I shall reopen, given more information.
