### ISSUE TITLE
1.16.4 request

### ISSUE THREAD

**Issue by McKitten** [coolsimulations/ServerStop#2]
Any chance you can post an update so this is usable with 1.16.4 please.
I had hoped it was flexible like some other server files seem to but forge refuses to load it.

**Comment by coolsimulations** [comment]
Yes I do plan on updating all my mods to 1.16.4, I did a post on the discord server saying: _Just a heads up that even though 1.16.4 is out, I won’t be updating my mods to it for another 2 weeks_ (now one week) _cause I don’t have the time_

**Comment by McKitten** [comment]
Thank you. 
I don't actually have you on discord atm and was only going off what was on curseforge.

GL with exams or whatever is distracting you :)

**Comment by coolsimulations** [comment]
Thanks, that is actually what I'm doIng :joy: I just saw in the Forge 35.0.5 changelog _Support backwards loading 1.16.3 mods in 1.16.4, because we are able to do that. Tweak loading a bit to be smarter about dependency errors of various kinds._ Haven't tested that myself but could worth a try in the meantime.
